services:
  web:
    build: .
    image: web
    container_name: web
    restart: unless-stopped
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
